// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbin8HV-zrVXJwdbe7wOKFaexobdFTwYc',
    appId: '1:235085206452:web:d11650cbfbfb63d84658e1',
    messagingSenderId: '235085206452',
    projectId: 'appmobile-10ca0',
    authDomain: 'appmobile-10ca0.firebaseapp.com',
    databaseURL: 'https://appmobile-10ca0-default-rtdb.firebaseio.com',
    storageBucket: 'appmobile-10ca0.appspot.com',
    measurementId: 'G-Z1SNTPGKDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsEy43hyCon6RZRErDeeMKhE0Ctf8gsn0',
    appId: '1:235085206452:android:cd9e4500cf4972b94658e1',
    messagingSenderId: '235085206452',
    projectId: 'appmobile-10ca0',
    databaseURL: 'https://appmobile-10ca0-default-rtdb.firebaseio.com',
    storageBucket: 'appmobile-10ca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHJv9gdRCNHs9u9Y2wkhpVhBAkdeonLQQ',
    appId: '1:235085206452:ios:41d2b6c63737e4454658e1',
    messagingSenderId: '235085206452',
    projectId: 'appmobile-10ca0',
    databaseURL: 'https://appmobile-10ca0-default-rtdb.firebaseio.com',
    storageBucket: 'appmobile-10ca0.appspot.com',
    iosClientId: '235085206452-bfmvb78rek9sac8p7qdseooqjkn7cnhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHJv9gdRCNHs9u9Y2wkhpVhBAkdeonLQQ',
    appId: '1:235085206452:ios:41d2b6c63737e4454658e1',
    messagingSenderId: '235085206452',
    projectId: 'appmobile-10ca0',
    databaseURL: 'https://appmobile-10ca0-default-rtdb.firebaseio.com',
    storageBucket: 'appmobile-10ca0.appspot.com',
    iosClientId: '235085206452-bfmvb78rek9sac8p7qdseooqjkn7cnhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appmobile',
  );
}
